### ISSUE TITLE
Install process shouldn't reinitiate virtualenv if it already exists.

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#17]
After the first install, the app's python virtual env will already be created and does not need to be recreated upon the next install. Skipping this step will speed up the reinstall step.

**Comment by carnesen** [comment]
@ericvanbuhler Agreed, that step is a bit too time-consuming to re-run every time. What would you suggest for our "we can skip this step" check? For example, for model installation the "skippable" criteria is "the model directory already exists and the alwaysai.model.json file has the correct `version` for the one that we are trying to install".

**Comment by carnesen** [comment]
Fixed! https://github.com/alwaysai/cli/blob/42c1f4b85c62c6760b2a70e9022f4988e39889e3/src/app-installer/index.ts#L27-L38
