### ISSUE TITLE
`app target start` command does not properly clean up app when brought down.

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#18]
For a remote device, when the `app target start` command is exited with CTRL-C, the running app is not properly brought down. The app will clean up properly if the CTRL-C is done in an ssh session, so it seems that the shutdown command is not being propagated to the device over the ssh session.

**Comment by carnesen** [comment]
As I understand it, when a user launches a shell in iTerm or whatever, the OS allocates to it a "pseudo-tty" (TTY), which is basically a readable pipe/stream that represents input from the keyboard, and a pair of pipes that represent output to the terminal screen, stderr and stdout. When the user launches the alwaysAI CLI, our Node.js process inherits the TTY. Currently when the command is `app target start` and the target protocol is 'ssh:', we (synchronously) launch `ssh` as a child and let it take control of the TTY. So when you are running `app target start` and hit CTRL-C, it's the `ssh` process that is receiving the "control character" and deciding what to do. Apparently in that case it's default behavior is to leave the remote python process running and just let itself exit, at which point the (sync) child spawn concludes, and the CLI exits having nothing left to do. Probably the best approach here is to try to launch the remote process in such a way that it exits if the thing that launched it hangs up. That would handle the explicit CTRL-C scenario as well as other various unintended disconnect scenarios.

**Comment by carnesen** [comment]
@ericvanbuhler I am playing around with this and for this simple python app:
```
import time

def main():
    while True:
        time.sleep(1)
if __name__ == "__main__":
    main()
```
The CTRL-C is behaving as expected. I seem to recall that edgeIQ apps have never responded well to CTRL-C. Can you point me to a specific app target so I can try to reproduce this?

**Comment by ericvanbuhler** [comment]
This issue seems to be resolved on the latest CLI. We can close it.
