### ISSUE TITLE
alwaysai shell doesn't activate venv

### ISSUE THREAD

**Issue by aulloa** [alwaysai/cli#21]
It would be a more seamless experience if the shell detected the venv and activated it, instead of having the user to it manually.

**Comment by carnesen** [comment]
@aulloa Currently the `shell` command is something like `ssh host "cd <appdir> && /bin/bash"`. Sounds like you want the command to be `ssh host "cd <appdir> && source <something> && /bin/bash"`. Does that sound about right? If so, what's the `<something>`?

**Comment by carnesen** [comment]
Fixed
