### ISSUE TITLE
Simplify the `app.py` created by`app init`

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#28]
For now, I think a cleaner workflow would be to clone or download the example apps and work with those apps rather than a sample *app.py* from the CLI. Removing the *app.py* from the CLI decouples the app version from the CLI, and also resolves the issue of model version mismatches, since the example apps already have the correct model version specified.

Once we have the ability to _publish_ apps, I think we could go back to a process where the CLI could automatically pull down an app.

**Comment by carnesen** [comment]
My philosophy is that after `app init` the user should have at least the skeleton of a working application, including an `app.py` file. I'm ok with it being just a stub for now, like 10 lines of code, no models. I'm also ok with putting in some fanciness to choose a "starter" app or something down the line.

**Comment by ericvanbuhler** [comment]
Agreed, let's go with a simple starter `app.py` file for now that won't be so tightly coupled with our edgeIQ releases.

**Comment by carnesen** [comment]
Closed by https://github.com/alwaysai/cli/pull/38 . Thanks Eric!
