### ISSUE TITLE
Support camera access on docker image on Linux host

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#29]
A simple solution that works on linux is to provide the two following arguments to `docker run`:
```
--privileged --volume /dev:/dev
```

The above arguments may not work on Mac, so more research is needed. On Windows, we may be able to use WSL to get around this issue.

**Comment by carnesen** [comment]
@ericvanbuhler We've discovered that giving the container access to the cameras on Mac and Windows is a much more complicated beast than on Linux. I'd like to restrict the scope of this particular issue to getting into place the proper flags for accessing the attached cameras from inside of a container on a Linux host. https://github.com/alwaysai/cli/pull/33 adds the `--privileged` flag to every docker command in the `docker:` or `ssh+docker:` protocols. Is that sufficient or do we need to volume-map the device directory too?

**Comment by carnesen** [comment]
Closed by https://github.com/alwaysai/cli/pull/37. Thanks Eric!
