### ISSUE TITLE
models add

### ISSUE THREAD

**Issue by ryanmalone** [alwaysai/cli#35]
another one 

![image](https://user-images.githubusercontent.com/2570551/58663468-73966780-82e1-11e9-9f8e-6a34c36f5efe.png)

**Comment by carnesen** [comment]
@ryanmalone  Can you please send the complete output of `alwaysai --version`.

**Comment by carnesen** [comment]
@ryanmalone We'll close this issue now since we haven't heard back from you. Please feel free to re-open if you'd like to pursue this further.
