### ISSUE TITLE
Can't communicate with NCS in v0.1.2

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#67]
It looks like the change to pass user ID to the container prevents communication with the NCS. Strangely, the device is still discoverable, it fails at a later step.

**Comment by carnesen** [comment]
@ericvanbuhler We are still mounting the /dev directory and passing the --privileged flag. Do you know what else we would need to do provide to the container for full access? Ref: https://github.com/alwaysai/cli/blob/80bc796772474843e71f22bd40d1eade2e9f6555/src/spawner/ssh-docker-spawner.ts#L24-L37
